import { createSlice } from '@reduxjs/toolkit';

import { authenticateUser } from './thunks';
import { AuthState } from './types';

const INITIAL_STATE: AuthState = {
  user: '',
  timestamp: '',
  status: 'idle',
  isAuthenticated: false,
  error: undefined,
};

export const authSlice = createSlice({
  name: '@auth',
  initialState: INITIAL_STATE,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    logout: () => INITIAL_STATE,
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(authenticateUser.pending, (draft) => {
        draft.status = 'loading';
      })
      .addCase(authenticateUser.fulfilled, (draft, { payload }) => {
        draft.status = 'idle';
        draft.isAuthenticated = true;
        draft.user = payload.user;
        draft.timestamp = payload.timestamp;
      })
      .addCase(authenticateUser.rejected, (draft, action) => {
        draft.status = 'failed';

        draft.error = action.payload?.error.message;
      });
  },
});

export const authActions = { ...authSlice.actions, authenticateUser };

export const authReducer = authSlice.reducer;
